@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

title Component Diagram for

Container_Boundary(b, "label") {
    Component(c, "label", "technology", "description")
    ComponentDb(cdb, "label", "technology", "description")
}

@enduml
