@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

title System Context Diagram for

System(s, "label", "description")
SystemDb(sdb, "label", "description")
SystemDb_Ext(sdbe, "label", "description")
System_Ext(se, "label", "description")

@enduml
