@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

title Container Diagram for

System_Boundary(b, "label") {
    Container(c, "label", "technology", "description")
    ContainerDb(cdb, "label", "technology", "description")
}

@enduml
