@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

title Dynamic Diagram for

Container(ctr, "label", "technology", "description")

Container_Boundary(b, "label") {
    Component(cmp, "label", "technology", "description")
}

ContainerDb(cdb, "label", "technology", "description")

Rel_R(ctr, cmp, "1. label", "technology")
Rel(cmp, cdb, "2. label", "technology")

@enduml
