@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

title System Landscape Diagram for

Boundary(b, "label", "type") {
    System(s, "label", "description")
}

@enduml
